### PR TITLE
better label naming for the GUI

### PR DESCRIPTION
**Pull request by NSShannon**

### CODE REVIEW

**Comment by truongnm-3365** [comment]
image
How to fix this error

**Comment by NSShannon** [comment]
How do I reproduce this error? It doesn't seem to have anything to do with this commit

**Comment by PwccaCode** [comment]
> How do I reproduce this error? It doesn't seem to have anything to do with this commit

it doesn't have anything to do with this branch

**Comment by JohnnyOlli** [comment]
image
My friend has the same error. Please fix, very cool software

**Review by ghost — APPROVED** [review]
Naming convention changes look good to me.

**Pull request closed without merging**
