### PR TITLE
Add Chinese language support.PageUp and PageDown button to change skin.

### PR DESCRIPTION
**Pull request by ztmzzz**
Add Chinese language support.
Add use the PageUp and PageDown button to change skin.

### CODE REVIEW

**Comment by ghost** [comment]
Nice but there should be an option to use the PageUp and PageDown button.

**Comment by ztmzzz** [comment]
add the option

**Comment by R3nzTheCodeGOD** [comment]
also add the option to change the skin with the desired key using the KeyBind class

**Comment by ztmzzz** [comment]
now i added this,thanks for telling me

**Comment by AliYa-chen** [comment]
It crashed on Chinese servers，
Can someone update the base address？？？
A good man lives a long life

**Comment by R3nzTheCodeGOD** [comment]
Still have problems, but it's ok, I will merge and fix it.

**Comment by R3nzTheCodeGOD** [comment]
Thanks for your contribution Why didn't github show you as a contributor?

github is really weird

**Comment by AbrnYa** [comment]
> 

I'm sorry that GitHub is not very friendly in China. I didn't push it to GitHub because DNS pollution in China is too serious and the integrity of the pushed documents cannot be guaranteed

**Pull request merged**
