### PR TITLE
Spell Tracker + Turret Range + Player Attack Range

### PR DESCRIPTION
**Pull request by R3nzTheCodeGOD**
## in-game images

image
image

### CODE REVIEW

**Comment by Xarond12** [comment]
is it bannable?

**Comment by magicaljgl** [comment]
Hi sorry to bother you, can you fix udyr spirit guard skin; animations doesn't work, thank u a lot

**Comment by seth007-moo** [comment]
Not recommend to use or add to skin injector cause this could get suspended activities and might get banned!
https://support-leagueoflegends.riotgames.com/hc/en-us/articles/225266848-Third-Party-Applications
But as the owner said at Note, it is optional.

**Comment by 04255** [comment]
nice,i want make a avoid and Skill range coil

**Comment by sonitaaaaa** [comment]
Option to choose between different announcers, in 12.12 is Star Guardian voice

**Comment by hdhue** [comment]
Hi, this happens when i try to use it. i play on eune
yas

**Comment by R3nzTheCodeGOD** [comment]
@hdhue 
```cpp
{
	{
		"56 8B F1 8B 06 8B 80 ? ? ? ? FF D0 84 C0 74 ? 8B 86 ? ? ? ? 8D 8E ? ? ? ? 8B 40 ? FF D0",
		"E8 ? ? ? ? 84 C0 74 ? 8D 8F ? ? ? ? E8 ? ? ? ? 84 C0 74 ? 85 F6"
	}, true, false, 0, &offsets::functions::IsAlive
}
```

**Comment by 1678895471** [comment]
**If I can, I hope I can add-----TFT SKIN**    : -)

**Comment by hdhue** [comment]
> @hdhue
> 
> ```c++
> {
> 	{
> 		"56 8B F1 8B 06 8B 80 ? ? ? ? FF D0 84 C0 74 ? 8B 86 ? ? ? ? 8D 8E ? ? ? ? 8B 40 ? FF D0",
> 		"E8 ? ? ? ? 84 C0 74 ? 8D 8F ? ? ? ? E8 ? ? ? ? 84 C0 74 ? 85 F6"
> 	}, true, false, 0, &offsets::functions::IsAlive
> }
> ```

I'm kinda dumb what do i do with that? 😅

**Comment by 04255** [comment]
> 

can you share it? i want to use

**Comment by dozzzz02** [comment]
Can you build this with CMake? I only see the VS solution.

E: Never mind, just downloaded VS, great work as always

**Comment by dozzzz02** [comment]
I just built it, and it's perfect, but I still get one of the pattern errors at the start as Darius, if that matters

**Comment by i1u5** [comment]
AtkRange and WorldToScreen offsets changed with 12.13

edit: new WorldToScreen (idk about AtkRange)
```cpp
{
	{
		"E8 ? ? ? ? 83 C4 08 83 F8 01 75 16",
		"E8 ? ? ? ? 8D 44 24 10 50 8B 44 24 54"
	}, true, false, 0, &offsets::functions::WorldToScreen
}
```

**Comment by parkyoungsoo** [comment]
plz update 12.13 
always good use
thank you

**Comment by R3nzTheCodeGOD** [comment]
This pull request is to show what you can develop using the source code of R3nzSkin.
I will not be updating this pull request in order not to derail the R3nzSkin project.
With a little knowledge of IDA and ReClass, you can easily update this pull request.

**Comment by dozzzz02** [comment]
> This pull request is to show what you can develop using the source code of R3nzSkin. I will not be updating this pull request in order not to derail the R3nzSkin project. With a little knowledge of IDA and ReClass, you can easily update this pull request.

Is it possible to code in opponent Attack Range? And positions inside Fog of War?

**Comment by xuuaaannnn** [comment]
can someone share WorldToScreen offsets sig?

**Comment by sakula6** [comment]
It has been completely disabled and can no longer be used. Look forward to updating

**Comment by sakula6** [comment]
It has been completely disabled and can no longer be used. Look forward to updating

**Comment by Npc2017** [comment]
Hello, can you share the characteristics of LOL 12.18 or 12.19 from the world to the screen? thank

**Comment by BarteQ778177** [comment]
> It has been completely disabled and can no longer be used. Look forward to updating

?

**Pull request closed without merging**
