### PR TITLE
13.18 Pattern Update 

### PR DESCRIPTION
**Pull request by tntd2k2**
I've updated some outdated pattern for 13.18
It's working good with me.
image

### CODE REVIEW

**Comment by sanzi8** [comment]
how to use it？brother

**Comment by tntd2k2** [comment]
> how to use it？brother

you can clone my fork and build it yourself

**Comment by HoangDuong1310** [comment]
cho tôi xin discord để nchn xíu được k ? ✌️

**Comment by tntd2k2** [comment]
> cho tôi xin discord để nchn xíu được k ? ✌️

Discord: youngboizseeyul7

**Comment by SimpleCoder321** [comment]
how do you find the codes that you replaced?

image

**Comment by tntd2k2** [comment]
> how do you find the codes that you replaced?
> image

Inject a dll for deref gamespace then dump exe using [LeagueDumper](https://github.com/tarekwiz/LeagueDumper). Then open it with IDA and make new sigs

**Comment by HoangDuong1310** [comment]
> > cho tôi xin discord để nchn xíu được k ? ✌️
> 
> Discord: youngboizseeyul7

check requestt

**Pull request closed without merging**
