### PR TITLE
Update memory.hpp

### PR DESCRIPTION
**Pull request by Papryczekk**
Updated for patch 14.6

### CODE REVIEW

**Comment by M1nt31** [comment]
is this a fix for the bug thats been going on lately?

**Comment by ulysessad** [comment]
how to put it?

**Comment by creatineabuser** [comment]
sexy

**Comment by M1nt31** [comment]
> Updated for patch 14.6

can you tell us how to swap the memory files with renz's code
cause ive been trying for 30 minutes and i cant figure it out

**Comment by Rakkagg** [comment]
update for 14.8

**Pull request closed without merging**
